In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("fivethirtyeight")

In [3]:
data = pd.read_csv('../data/processed/regression_res.csv')
data

                                    Variable    Coef   lower   upper
0                                       date   0.758   0.215   1.301
1                      C1 School closing org  -1.027 -26.938  24.884
2                   C2 Workplace closing org   0.805 -15.224  16.833
3                C3 Cancel public events org -35.935 -69.067  -2.802
4          C4 Restrictions on gatherings org  -6.954 -12.999  -0.910
5              C5 Close public transport org   6.277  -3.046  15.599
6          C6 Stay at home requirements org  -21.311 -38.499  -4.123
7   C7 Restrictions on internal movement org  26.158  -0.709  53.026
8       C8 International travel controls org -23.644 -46.199  -1.088
9                               log_case_org  13.562   8.098  19.026
10                             log_death_org -11.962 -17.184  -6.739
11                              log_case_dst  -6.199 -12.602   0.204
12                             log_death_dst   6.617  -0.380  13.614